-------------------------------------------------------------------------------
Test set: com.example.MainTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.090 s <<< FAILURE! -- in com.example.MainTest
com.example.MainTest.Function_2_should_return_II -- Time elapsed: 0.066 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: "II"
 but was: "I"
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at com.example.MainTest.Function_2_should_return_II(MainTest.java:17)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

