-------------------------------------------------------------------------------
Test set: com.example.MainTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.092 s <<< FAILURE! -- in com.example.MainTest
com.example.MainTest.III_should_return_3 -- Time elapsed: 0.065 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: "3"
 but was: ""
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at com.example.MainTest.III_should_return_3(MainTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

